kws_eim:
  ros__parameters:
    ei_server_url: "http://localhost:1338"
    audio_topic: /hri/processedAudioChunk
    KEYWORD_TOPIC: REPLACE
    detection_cooldown: 1.0
    sensitivity_threshold: 0.45
    sample_rate: 16000
    window_size_s: 1.0
    hop_ratio: 0.25
    audio_gain: 1.0
    noise_label: "noise"
    save_detection_audio: false
    audio_save_dir: "/workspace/src/hri/packages/speech/assets/kws_detections"
