voice_detection:
  ros__parameters:
    PROCESSED_AUDIO_TOPIC: REPLACE
    VAD_AUDIO_TOPIC: REPLACE
    VOICE_ACTIVITY_TOPIC: REPLACE
    ENABLE_VAD: true
    ENERGY_THRESHOLD: 600.0
    CORRELATION_THRESHOLD: 0.6
    SIMILARITY_THRESHOLD: 0.70
    SILENCE_LIMIT: 2.0
    SAMPLE_RATE: 16000
    DEBUG: false
